import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "@/redux/AppProvider";
import { Toaster } from "react-hot-toast";
import Header from "@/components/layout/Header";
import Checkauthentication from "@/components/CheckAuthentication";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Checkauthentication>
            <Header />
            {children}
          </Checkauthentication>
        </AppProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
